/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
 
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] arr = new int[26];
        for(int i = 0; i < s.length(); i++){
            arr[s.charAt(i) - 'a']++;
        }
        for(int i = 0; i < t.length(); i++){
            arr[t.charAt(i) - 'a']--;
        }
        
        char c = ' ';
        for(int i = 0; i < 26; i++){
            if(arr[i] != 0){
                c = (char) ( i + 'a');
            }
        }
        return c;
    }
}
